version: '2.21'

services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: mi_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admlinux
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - ./data:/data/db
      - ./data/log:/var/log/mongodb
    ports:
      - "27017:27017"
